### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by brn2prgrm** [lukasroegner/homebridge-sonos-multiroom#13]
Is there a way to have a boolean option for what logic happens when this plugin finds that nothing is already playing?

Ideally I would like to be able to have the plugin join a group if it is already playing, but not start playing something if nothing is being played?  The plugin would simply ignore the switch request, until it is turned off/on again.

Maybe there's just a line or two that I can comment out, but I think others would find value in this config option as well!

Thanks for any input!

**Comment by Fofer** [comment]
Just chiming in to say, that’s currently how this plugin works for me, and I didn’t do any extra configuration. It only groups if something is already playing. And it doesn’t start playing something, if nothing was being played. 

I’m not sure what’s different about your setup. But I don’t think this needs to be added as it’s already there.

**Comment by Fofer** [comment]
My apologies! I deleted my previous reply to instead report that I am, in fact, experiencing this same issue.  

My bathroom and kitchen Sonos are often "parked" on whatever music station they were playing last. And now, whenever I go in those rooms, they will start playing that music, due to the motion sensing and this automation. I don't know how to clear out the station that's parked, so I've had to disable the automation entirely.

I really only want automatic grouping to occur (thanks to this excellent plugin) when there is something playing in the other rooms. That's precisely what I've wanted for a long time and this plugin handles it *beautifully.*  I've shared my enthusiasm about this plugin in many forums.  It's probably my favorite smarthome thing :)

But I really don't want automatic playback to ever occur, especially if nothing else is playing anywhere else.  It's a bit jarring (especially late at night) and unfortunately diminishes the appeal of using this plugin.  I'm hoping there's an edit or some additional configuration we can do, so that homebridge-sonos-multiroom only *groups* rooms as desired, and doesn't simply "start playback" if nothing is playing in that room or elsewhere. Which could be achieved with a different, simple automation anyway ("if motion, play music.")

Thanks for the consideration or any additional assistance. Much appreciated!

**Comment by lukasroegner** [comment]
I've added a new parameter `isAutoPlayDisabled` to the config. You can now set the parameter to `true` if you don't want the Sonos device to start the recently used source if none of the other devices is currently playing. Keep in mind that this also makes the switches useless if no Sonos is currently playing.

**Comment by Fofer** [comment]
Apologies for not replying to this sooner, the update is working perfectly for me! Thank you so much!
